blog/urls.py
from django.urls import path,include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('sobre-nos/', views.about, name='about'),

    path('iniciar/', views.iniciar, name='iniciar'),
    path('iniciar/<int:flag>/', views.iniciar, name='iniciar'),
    path('arvore/', views.arvore, name='arvore'),
    path('arvore/resposta/', views.resposta, name='resposta'),
    path('arvore/concluida/', views.arvoreConcluida, name='arvoreConcluida'),
    path('testar/', views.testar, name='testar'),
    path('testar/arvore/<int:arvore_id>/tela/<int:tela_id>/', views.teste, name='teste'),
    path('testar/resposta/<int:tela_id>/', views.respostaTeste, name='respostaTeste')
    
    # path('forms/', views.forms, name='forms'),
    # path('formulario/<int:form_id>', views.formulario, name='formulario'),
    # path('formulario/<int:form_id>/pergunta/<int:pergunta_num>', views.pergunta, name='pergunta'),
    # path('formulario/', views.formConcluido, name='formConcluido'),
]

site_login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# mexer com mídia
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Arvore(models.Model):
    nome = models.CharField('Nome da Árvore', null=True, blank=False,max_length=120)
    submetida = models.BooleanField('Já foi submetida à resposta', default=False, blank=False)
    prim_tela = models.OneToOneField('Tela', on_delete=models.CASCADE, blank= True, null = True, related_name='+')
    timeout = models.IntegerField(blank=False, null=False, default=0)

    def __str__(self):
        return 'Árvore ' + str(self.id) + ': ' + self.nome

class Usuario(models.Model):

    escolaridades = [('FI',   'Ensino Fundamental Incompleto'),
                     ('FC',   'Ensino Fundamental Completo'),
                     ('MI',   'Ensino Medio Incompleto'),
                     ('MC',   'Ensino Medio Completo'),
                     ('SI',  'Ensino Superior Incompleto'),
                     ('SC',  'Ensino Superior Completo')
    ]
    generos = [('Masc', 'Masculino'), ('Femin', 'Feminino'), ('Outro', 'Outro')]

    nome = models.CharField('Nome do Usuário', max_length=120, blank=False, null=True)
    email = models.EmailField('Email',blank=False,null=True,unique=True)
    idade = models.IntegerField(blank=False, null=True)
    genero = models.CharField('Gênero', blank=False,max_length=15, choices=generos, null=True)
    escolaridade = models.CharField('Escolaridade', choices=escolaridades, max_length=3, blank=False, null=True)
    curso = models.CharField('Curso', max_length=120, blank=False, null=True)
    nacionalidade = models.CharField('Nacionalidade', max_length=120, blank=False, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null = True, editable=False)

    # arvores ja respondidas
    arvores = models.ManyToManyField('Arvore', blank =True)
    # arvores = models.ManyToManyField('Arvore', blank =True, editable=False)


    def __str__(self):
        return self.nome


class Tela(models.Model):
    arvore = models.ForeignKey(Arvore,on_delete=models.CASCADE, null = True)
    nome = models.CharField('Nome da Tela', null=True, blank=False, max_length=120)
    question = models.OneToOneField('Question', on_delete=models.DO_NOTHING, null=True, blank=True, verbose_name='Pergunta')
    
    ultimo = models.BooleanField('Final', default=False, blank=False)

    # estimulos:
    video = models.URLField(max_length=250, null=True, blank=True)
    imagem = models.ImageField(upload_to='estimulos/', blank=True, null=True, help_text='A ordem de prioridade dos estímulos é de Vídeo > Imagem > Texto')
    texto = models.CharField(null=True, blank=True, max_length=250)

    def __str__(self):
        return 'Árvore ' + str(self.arvore.id) + ': ' + self.nome



class Question(models.Model):
    texto = models.CharField('Texto da questão', max_length=120, blank=False, null=True)
    tela_filha = models.ManyToManyField(Tela, through='Escolha', related_name='questions')
    
    class Meta:
        verbose_name = 'Pergunta'


    def __str__(self):
        try:
            return 'Árvore ' + str(self.tela.arvore.id) + ': ' + self.texto
        except:
            return self.texto




class Escolha(models.Model):

    nome = models.CharField('Nome da Escolha', null=True, blank=False, max_length=120)

    # Question pai
    question = models.ForeignKey(Question,on_delete=models.CASCADE, null = True, blank=True)

    # Tela filha
    tela = models.ForeignKey(Tela ,on_delete=models.CASCADE, null = True, blank=True)
    
    def __str__(self):
        return self.nome
    


class Raiz(models.Model):

    arvore = models.OneToOneField(Arvore, on_delete=models.CASCADE, null=True,blank=True, help_text="<h1><strong>Ao submeter uma árvore a ser respondinda no site, ela não poderá mais ser editada.</strong></h1>")

    # tempo de duração, etc
    def __str__(self):
        if self.arvore:
            return 'Árvore ' +  str(self.arvore.id) + ': ' + self.arvore.nome
        else:
            return 'Raiz vazia'

    class Meta:
        verbose_name_plural = "Raizes"

class Resposta(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING, null=True, editable=False)
    arvore = models.ForeignKey(Arvore, on_delete=models.DO_NOTHING, null=True, editable=True)
    question = models.ForeignKey(Question, on_delete=models.DO_NOTHING, null=True, editable=True)
    escolha = models.ForeignKey(Escolha, on_delete=models.DO_NOTHING, null=True, editable=True)
    tempo = models.IntegerField(blank=True, null=True)

    pub_data = models.DateField('Data da resposta', null=True, blank=True, editable=True)

    def __str__(self):
        return self.usuario.nome + ': ' + self.question.texto



# ================================================



# class Pergunta(models.Model):
#     nome = models.CharField('Nome da pergunta', max_length=120, blank=False)
#     pergunta = models.CharField('Pergunta', max_length=120, blank=False)

#     def __str__(self):
#         return self.nome

# class Formulario(models.Model):

#     nome = models.CharField('Nome do formulário', max_length=120, blank=False)
#     descricao = models.CharField('Descricao', max_length=120, blank=True, null=True)
#     data_inicial = models.DateField('Data de Início', auto_now=False, auto_now_add=False, null=True)
#     data_final = models.DateField('Data Final', auto_now=False, auto_now_add=False, null=True)
#     perguntas = models.ManyToManyField(Pergunta, blank=True)

#     def __str__(self):
#         return self.nome


# class PerfilGeral(models.Model):

#     nome = models.CharField('Nome do Perfil', max_length=120, blank=False)
#     numero_de_usuarios = models.PositiveIntegerField(blank=False, default=0)
#     formularios = models.ManyToManyField(Formulario, blank=True)

#     def __str__(self):
#         return self.nome

# class Alternativa(models.Model):
#     texto = models.CharField('Texto da alternativa', max_length=120, blank=False, null=True)

#     # cada alternativa está ligada a apenas uma pergunta
#     pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)

#     # Dados: quantas vezes escolhida, tempo médio de tempo de respota, etc...

#     def __str__(self):
#         return self.texto

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Usuario, Resposta
from .models import Arvore, Question, Escolha, Raiz, Tela

from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.decorators import login_required            # Limita o acesso de uma url apenas para usuários logados

def apagarSessao(request):
    keyArray = []
    # apaga dados da sessão mas sem fazer logout
    for key, value in request.session.items():
        # não deletar keys que indicam login
        if key[0] != '_':
            keyArray.append(key)

    for key in keyArray:
        del request.session[key]

def about(request):
	return render(request, 'blog/about_us.html')

def home(request):
    return render(request, 'blog/home.html')


@login_required
def arvore(request):

    usuario = request.user.usuario

    try:
        tela_atual = Tela.objects.get(pk=request.session['tela_atual']) 
    except:
        return redirect('/')

    escolhas = tela_atual.question.escolha_set.all()
    if tela_atual.video:
        url = tela_atual.video + '?autoplay=1&controls=0&disablekb=1&modestbranding=1&rel=0&showinfo=0'
    else:
        url = None
    context= {
        'tela':tela_atual,
        'escolhas': escolhas,
        'url_tela':url,
        'tela_num': request.session['tela_num']
    }

    # # Atualizar arvore para submetida
    # if tela_atual.arvore.submetida == False:
    #     tela_atual.arvore_do_dia.submetida = True
    #     tela_atual.arvore_do_dia.save()

    return render(request, 'blog/tela.html', context)

def arvoreConcluida(request):
    return render(request, 'blog/arvoreConcluida.html',{})

@login_required
def resposta(request):
    if request.method == 'GET':
        return redirect('/')

    usuario = request.user.usuario
    # verificar se está respondendo algum questionário
    try:
        tela = Tela.objects.get(pk=request.session['tela_atual'])
    except:
        messages.warning(request,'Você saiu do questionário.')
        return redirect('/')


    arvore      = tela.arvore
    question    = tela.question

    # ver se já existe um tempo inicial para a pergunta
    ini_tempo_num = 'ini_tempo' + str(request.session['tela_num'])

    try:
        request.session[ini_tempo_num]
    except:
        request.session[ini_tempo_num] = request.POST['ini_tempo']

    # verificar timeout
    if arvore.timeout and ((int(request.POST['fim_tempo']) - int(request.session['ini_tempo0'])) > arvore.timeout * 60 *1000):
        messages.error(request, 'Tempo esgotado.')
        return redirect('/')

    # validar resposta
    try:
        escolha_id = request.POST['escolha']
    except (KeyError, Escolha.DoesNotExist):

        if tela.video:
            url = tela.video + '?autoplay=1&controls=0&disablekb=1&modestbranding=1&rel=0&showinfo=0'
        else:
            url = None

        return render(request, 'blog/tela.html', {
            'tela':tela,
            'escolhas': question.escolha_set.all(),
            'error_message': "Você não escolheu uma alternativa.",
            'url_tela': url,
            'tela_num': request.session['tela_num']
        })
    escolha = Escolha.objects.get(pk=escolha_id)


    # verificando duplicata
    for i in range(1, request.session['tela_num']):    
        if question.id == request.session['question' + str(i)]:
            prox_tela = Tela.objects.get(pk=request.session['question' + str(i)])
            request.session['tela_atual'] = prox_tela.id
            url = '/arvore/'
            
            return redirect(url)

    # atualizar fim_tempo
    fim_tempo_num = 'fim_tempo' + str(request.session['tela_num'])
    request.session[fim_tempo_num] = request.POST['fim_tempo']

    request.session['tela_num'] += 1
    # adicionando respostas a sessão
    question_num = 'question' + str(request.session['tela_num'])
    request.session[question_num] = question.pk
    escolha_num = 'escolha' + str(request.session['tela_num'])
    request.session[escolha_num] = escolha.pk
    tempo_num = 'tempo' + str(request.session['tela_num'])
    request.session[tempo_num] = (int(request.session[fim_tempo_num]) - int(request.session[ini_tempo_num]))

    usuario.tela_num = request.session['tela_num']

    if tela.ultimo:

        usuario.arvores.add(arvore)
        usuario.save()

        # Salvar repostas já que ele chegou no final
        pub_data    = timezone.now().date()
        for i in range(1, request.session['tela_num'] + 1):
            question = get_object_or_404(Question, pk=int(request.session['question' + str(i)]))
            escolha = get_object_or_404(Escolha, pk=int(request.session['escolha' + str(i)]))
            tempo = request.session['tempo' + str(i)]
            Resposta.objects.create(usuario=usuario, arvore=arvore, question=question, escolha=escolha, tempo=tempo, pub_data=pub_data)
        apagarSessao(request)
        url = '/arvore/concluida/'
    else:
        request.session['tela_atual'] = escolha.tela.id
        url = '/arvore/'

    return redirect(url)


@login_required
def iniciar(request, flag=None):
    
    usuario = request.user.usuario
    if not flag:
        # se não tiver flag, renderizar iniciar normalmente
        try:
            # pegar árvore disponível
            arvore_do_dia = Raiz.objects.all()[0].arvore
            if arvore_do_dia in usuario.arvores.all(): # arvore já respondida 
                return render(request, 'blog/arvoreConcluida.html',{})
        except:
            arvore_do_dia = None

        context = {
            'arvore':arvore_do_dia,
        }

        return render(request, 'blog/iniciar.html', context)

    # se tiver flag, iniciar questionário
    arvore_do_dia = Raiz.objects.all()[0].arvore
    primeira_tela = arvore_do_dia.prim_tela.id


    try:
        usuario.tela_atual
        # saiu do questionario
        # invalidar questionario
        tela = Tela.objects.get(pk=request.session['tela_atual'])
        usuario.arvores.add(tela.arvore)
        del request.session['tela_atual']
        return redirect('/')
    except:
        request.session['tela_atual'] = primeira_tela
        

    # iniciar sessão
    request.session['username'] = request.user.username
    request.session['arvore'] = arvore_do_dia.id
    request.session['tela_num'] = 0
    request.session.set_expiry(600)  

    return redirect('blog:arvore')
    

def verificarArv(arv):
    # verificar se árvore foi criada corretamente
    try:
        return arv.prim_tela
    except:
        return False

@login_required
def testar(request):
    if not request.user.is_superuser:
        return redirect('blog:home')
    
    arvores = Arvore.objects.all()
    for arv in arvores:
        if not verificarArv(arv):
            messages.warning(request, f"Parece que a arvore '{arv.nome}' não possui uma primeira tela. Por favor, verifique se ela foi preenchida corretamente.")
            return redirect('blog:home')
    
    context = {
        'arvores': arvores
    }
    return render(request, 'blog/testar.html', context)


@login_required
def teste(request, arvore_id, tela_id):
    if not request.user.is_superuser:
        return redirect('blog:home')

    tela_atual = Tela.objects.get(pk=tela_id)
    escolhas = tela_atual.question.escolha_set.all()
    if tela_atual.video:
        url = tela_atual.video + '?autoplay=1&controls=0&disablekb=1&modestbranding=1&rel=0&showinfo=0'
    else:
        url = None
    context= {
        'tela':tela_atual,
        'escolhas': escolhas,
        'url_tela':url,
    }

    return render(request, 'blog/telaTeste.html', context)

@login_required
def respostaTeste(request, tela_id):
    if not(request.user.is_superuser) or request.method == 'GET':
        return redirect('blog:home')
    
    tela        = Tela.objects.get(pk=tela_id)
    arvore      = tela.arvore
    question    = tela.question

     
    try:
        escolha_id = request.POST['escolha']
    except (KeyError, Escolha.DoesNotExist):
        return render(request, 'blog/telaTeste.html', {
            'tela':tela,
            'escolhas': question.escolha_set.all(),
            'error_message': "Você não escolheu uma alternativa."
        })

    escolha = Escolha.objects.get(pk=escolha_id)   



    if tela.ultimo:
        return redirect('blog:testar')
    else:
        prox_tela = Tela.objects.get(pk=escolha.tela.id)
        url = '/testar/arvore/' + str(arvore.id) + '/tela/' + str(prox_tela.id)
        return redirect(url)



    


# ===================


# @login_required
# def forms(request):
#     usuario_logado = request.user                                    #user logado
#     usuario_logado = usuario_logado.usuario                          #usuario logado
#     perfil = usuario_logado.perfil_especifico                        #perfil do usuario logado
#     forms_disponiveis = perfil.formularios.order_by('-data_inicial') #formularios do perfil
#     forms_respondidos = usuario_logado.formularios.all()

#     if len(forms_disponiveis) == len(forms_respondidos):             # se todos os formulários foram respondidos
#         return render(request, 'blog/forms_respondidos.html', {})

#     elif len(forms_disponiveis) < len(forms_respondidos):
#         return HttpResponse('<h1 style="color:red">ERRO: Mais formulários respondidos do que disponíveis<h1>')

#     if usuario_logado.form_atual:                                    #Continuar de onde parou
#         ultima_perg = len(usuario_logado.alternativas.all())
#     else:
#         ultima_perg = None

#     context = {
#     'forms_disponiveis' : forms_disponiveis,
#     'forms_respondidos' : forms_respondidos,
#     'ultima_perg' : ultima_perg
#     }
#     return render(request, 'blog/forms.html', context)


# @login_required
# def formulario(request, form_id):
#     try:
#         formulario = Formulario.objects.get(pk=form_id)
#     except Formulario.DoesNotExist:

templates/blog/about_us.html
{% extends 'base.html' %}

{% block content %}
<div class="PaginaInicial">
	<div class="container">
		<h1>Sobre nós</h1>
		<p>Esta é a história do blog...</p>
	</div>
</div>

{% endblock %}

templates/blog/arvoreConcluida.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4" style="width:600px;">
        <div class="card mb-3 mt-4">
            <div class="card-body">
                <h3 >Obrigado por responder ao nosso questionário!</h1>
                <h2 class="lead">Novos questionários serão disponibilizados em breve.</h2>
            </div>
            <div><a  href='/' class="btn btn-primary btn-lg  ml-4 mb-4">Página Inicial</a></div>
        </div>
    </div>
    

{% endblock %}

templates/blog/form_concluido.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4" style="width:600px;">
        <div class="card mb-3 mt-4">
            <div class="card-body">
                <h1 class="lead">Parabéns! Você terminou esse formulário.</h1>
                <p>Formulários respondidos: {{forms_repondidos}}</p>
            </div>
            <div><a  href='/' class="btn btn-primary btn-lg  ml-4 mb-4">Página Inicial</a></div>
        </div>
        </div>
    

{% endblock %}

templates/blog/forms.html
{% extends 'base.html' %}

{% block content %}

    {% if user.usuario.form_atual %}
    <div class="container mt-4" style="width:600px;">
    <div class="card mb-3 mt-4">
        <div class="card-body">
            <h1 class="lead">Parece que você já está respondendo a um questionário.</h1>
            <p>Deseja voltar a respondê-lo?</p>
        </div>
        <div><a  href="{% url 'blog:pergunta' user.usuario.form_atual.id ultima_perg%}" class="btn btn-primary btn-lg  ml-4 mb-4">Responder</a></div>
    </div>
    </div>


    {% else %}


        <h1 class="text-center mb-3">Questionários disponíveis:</h1>
        {% if forms_disponiveis %}
            {% for formulario in forms_disponiveis %}

                {% if formulario in forms_respondidos %}
                {% else %}

                <div class="card mb-3 text-center">
                    <div class="card-body">
                        <a href="{% url 'blog:formulario' formulario.id %}">{{ formulario.nome }}</a>
                        <p class="lead">{{ formulario.descricao }}</p>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
    
        {% else %}
            <p>Nenhum formulário disponível</p>
        {% endif %}
    {% endif %}
{% endblock %}

templates/blog/forms_respondidos.html
{% extends 'base.html' %}


{% block content %}
<div class="card mb-3 mt-4">
    <div class="card-body">
        <p class="lead">Parabéns! Todos os formulários foram respondidos.</p>
    </div>
</div>
<div><a  href="/">Voltar para a página inicial.</a></div>

{% endblock %}

templates/blog/iniciar.html
{% extends 'base_arvore.html' %}

{% block formulario %}
<div class="m-auto">
    {% if arvore %}
        <p class='mt-4'>(Explicar regras do questionário)</p>
        <a style="text-decoration: none;" href= "{% url 'blog:iniciar' 1 %}"><button class="btn btn-primary btn-lg btn-block mt-4 mb-4">Iniciar questionário</button></a>
        <a style="text-decoration: none;" href= "/"><button class="btn btn-secondary btn-lg btn-block mt-4 mb-4">Voltar para a página inicial.</button></a>
    {% else %}
        <h3 class= 'mt-3'>No momento não há nenhum questionário disponível.</h3>
        <a style="text-decoration: none;" href= "/"><button class="btn btn-primary btn-lg btn-block mt-4 mb-4">Voltar para a página inicial.</button></a>
    {% endif %}
</div>
{% endblock %}

templates/blog/pergunta.html
{% extends 'base.html' %}


{% block formulario %}

<h1 class="text=-center mb-3 mt-4">{{ pergunta.pergunta }}</h1>

{% if error_message %}
<p class="alert alert-danger mb-2" style="display:inline-block; max-width:500px;">
    <strong>{{ error_message }}</strong>

</p> 
{% endif %}

<form action="{% url 'blog:resposta' formulario.id pergunta_num %}" method="POST" >
    {% csrf_token %}
    {% for alt in pergunta.alternativa_set.all %}
        {% if alt in user.usuario.alternativas.all %}
        <div class="form-check" > 
            <input 
            type="radio"
            name="alternativa"
            class="form-check-input"
            id="alternativa{{ forloop.counter }}"
            value="{{ alt.id }}"
            checked
            />
            <label for="alternativa{{ forloop.counter }}">{{alt.texto}}</label>
        </div>
        {% else %}
        <div class="form-check" > 
            <input 
            type="radio"
            name="alternativa"
            class="form-check-input"
            id="alternativa{{ forloop.counter }}"
            value="{{ alt.id }}"
            />
            <label for="alternativa{{ forloop.counter }}">{{alt.texto}}</label>
        </div>
        {% endif %}

    {% endfor %}
    
    <small class="text-muted" style="float: right;">
        {{pergunta_num|add:1}} de {{num_de_perguntas}}
    </small>

    <input type="submit" value="Responder" class="btn btn-primary btn-lg btn-block mt-4 mb-4"/>
</form>
{% if pergunta_num == 0 %}
    <a href="{% url 'blog:formulario' formulario.id %}" class="mb-4 btn btn-secondary">Voltar</a>
    
{% else %}
    <a href="{% url 'blog:pergunta' formulario.id pergunta_num|add:'-1' %}" class="mb-4 btn btn-secondary">Voltar</a>

    
{% endif %}

{% endblock %}

templates/blog/tela.html
{% extends "base_arvore.html" %}
{% load static %}

<link href="{% static 'js/app.js' %}">

{% block formulario %}

{% if tela.video %}
<div class='video'>
    <iframe max-width="1732" max-height="722" src={{url_tela}} frameborder="1" allow=" autoplay; encrypted-media; gyroscope; picture-in-picture">
    </iframe>
</div>


{% elif tela.imagem %}
<div class="text-center">
    <img src="{{tela.imagem.url}}" class="rounded mt-4" style="width:300px; height:280px;" alt="...">
</div>

{% elif tela.texto %}
<div class="text-center">
    <p class="mt-4">{{tela.texto}}</p>
</div>

{% endif %}


<form action="{% url 'blog:resposta' %}" method="POST" class="form-tela" id="form-tela" onsubmit="countTime()" >
    {% csrf_token %}

    <hr>
    
    {% if error_message %}
    <p class="alert alert-danger mb-2" style="display:inline-block; max-width:500px;">
        <strong>{{ error_message }}</strong>
    
    </p>


    {% endif %}
    

    <h1 class="text=-center mb-3 ">{{ tela.question.texto }}</h1>

    {% for escolha in escolhas %}
        <div class="form-check tela" > 
            <input 
            type="radio"
            name="escolha"
            class="form-check-input"
            id="escolha{{ forloop.counter }}"
            value="{{ escolha.id }}"
            />
            <label for="escolha{{ forloop.counter }}"><div class='botao-tela'>{{escolha.nome}}</div></label>
        </div>
    {% endfor %}
    <input
    type="number"
    name="ini_tempo"
    id="ini_tempo{{ tela_num }}"
    value=-1
    hidden
    />
    <input
    type="number"
    name="fim_tempo"
    id="fim_tempo{{ tela_num }}"
    value=-1
    hidden
    />

    <input type="submit" value="Responder" class="btn btn-primary btn-lg btn-block mt-4 mb-4" id="subBtn" />
    
</form>

</form>

<script type="text/javascript">
    // só seta a variável ini_tempo uma vez 
    if (sessionStorage.getItem("ini_tempo{{ tela_num }}") == null){
        const ini_tempo = new Date()
        sessionStorage.setItem("ini_tempo{{ tela_num }}", ini_tempo.getTime())
        document.getElementById("ini_tempo{{ tela_num }}").value = ini_tempo.getTime()
    }
    else{
        document.getElementById("ini_tempo{{ tela_num }}").value = sessionStorage.getItem("ini_tempo{{ tela_num }}")
    }

    function countTime(e){
        const fim_tempo = new Date()
        document.getElementById("fim_tempo{{ tela_num }}").value = fim_tempo.getTime()
    }

</script>

{% endblock %}

templates/blog/telaTeste.html
{% extends 'base_arvore.html' %}
{% load static %}

<link href="{% static 'js/app.js' %}">

{% block formulario %}

{% if tela.video %}
<div class='video'>
    <iframe max-width="1732" max-height="722" src={{url_tela}} frameborder="1" allow=" autoplay; encrypted-media; gyroscope; picture-in-picture">
    </iframe>
</div>


{% elif tela.imagem %}
<div class="text-center">
    <img src="{{tela.imagem.url}}" class="rounded mt-4" style="width:300px; height:280px;" alt="...">
</div>

{% elif tela.texto %}
<div class="text-center">
    <p class="mt-4">{{tela.texto}}</p>
</div>

{% endif %}


<form action="{% url 'blog:respostaTeste' tela.id %}" method="POST" class="form-tela">
    {% csrf_token %}

    <hr>

    {% if error_message %}
    <p class="alert alert-danger mb-2" style="display:inline-block; max-width:500px;">
        <strong>{{ error_message }}</strong>
    
    </p> 
    {% endif %}

    <h1 class="text=-center mb-3 ">{{ tela.question.texto }}</h1>

    {% for escolha in escolhas %}
        <div class="form-check tela" > 
            <input 
            type="radio"
            name="escolha"
            class="form-check-input"
            id="escolha{{ forloop.counter }}"
            value="{{ escolha.id }}"
            />
            <label for="escolha{{ forloop.counter }}"><div class='botao-tela'>{{escolha.nome}}</div></label>
        </div>
    {% endfor %}

    <input type="submit" value="Responder" class="btn btn-primary btn-lg btn-block mt-4 mb-4"/>
    
</form>

<!-- <script type="text/javascript">
    window.history.forward()

</script> -->

{% endblock %}

templates/blog/testar.html
{% extends 'base.html' %}

{% block content %}

{% for arv in arvores %}
<div class="container mt-5 mr-2 ml-2" style="border-radius: 10px; background-color: #f8f8f8;border:black 1px solid; max-width: 200px; min-height: 100px;display:inline-block;">
    <div class="row">
        <div class="col-md-10 m-auto" style>
            <p><a href = "{% url 'blog:teste' arv.id arv.prim_tela.id %}" style="text-decoration: none;cursor: pointer;"> Árvore {{arv.nome}}<br>id : {{arv.id}}</a> </p>
            
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}