account/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import LoginView,LogoutView
from .forms import LoginForm

app_name = 'account'

# mudar a variável template_name de LoginView de registration/login.html para account/login.html
urlpatterns = [

    # auth views
    path('',LoginView.as_view(template_name="account/login.html", redirect_authenticated_user=True)),
    path('login/', LoginView.as_view(template_name="account/login.html", redirect_authenticated_user=True,authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # django views
    path('registrar/', views.register, name='register'),
    path('perfil/', views.perfilVisualizar, name='perfilVisualizar'),
    path('perfil/atualizar', views.perfilAtualizar, name='perfilAtualizar')
    
]

blog/urls.py
from django.urls import path,include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('sobre-nos/', views.about, name='about'),

    path('iniciar/', views.iniciar, name='iniciar'),
    path('iniciar/<int:flag>/', views.iniciar, name='iniciar'),
    path('arvore/', views.arvore, name='arvore'),
    path('arvore/resposta/', views.resposta, name='resposta'),
    path('arvore/concluida/', views.arvoreConcluida, name='arvoreConcluida'),
    path('testar/', views.testar, name='testar'),
    path('testar/arvore/<int:arvore_id>/tela/<int:tela_id>/', views.teste, name='teste'),
    path('testar/resposta/<int:tela_id>/', views.respostaTeste, name='respostaTeste')
    
    # path('forms/', views.forms, name='forms'),
    # path('formulario/<int:form_id>', views.formulario, name='formulario'),
    # path('formulario/<int:form_id>/pergunta/<int:pergunta_num>', views.pergunta, name='pergunta'),
    # path('formulario/', views.formConcluido, name='formConcluido'),
]

site_login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# mexer com mídia
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8" />
	
	<link href="{% static 'css/style.css' %}" rel="stylesheet">

	<link rel="icon" href="{% static 'media/pratica_de_lembrar_icone.png' %}" />
	<link
		rel="stylesheet"
		href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
	/>
	<link
		rel="stylesheet"
		href="https://fonts.googleapis.com/icon?family=Material+Icons"
	/>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<meta
		name="viewport"
		content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"
	/>
	<!--
		manifest.json provides metadata used when your web app is installed on a
		user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
	-->
	<!-- <link rel="manifest" href="%PUBLIC_URL%/manifest.json" /> -->
	<!--
		Notice the use of %PUBLIC_URL% in the tags above.
	It will be replaced with the URL of the `public` folder during the build.
		Only files inside the `public` folder can be referenced from the HTML.
	
		Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
		work correctly both with client-side routing and a non-root public URL.
		Learn how to configure a non-root public URL by running `npm run build`.
	-->

	<title>Prática de Lembrar</title>
</head>
<body>
	{% include 'navbar.html' %}

		<!-- Messagem indicando que o usuário foi criado, só aparece quando o usuário acabou de se registrar -->
		{% if messages %}
			{% for message in messages %}
					<!-- <div class="alert alert-{{message.tags}}">
						{{ message }}
					</div> -->
					<div style='text-align: center;'>
						<p class="alert alert-{{message.tags}} mb-2 mt-2" style="display:inline-block; max-width:70%;">
							<strong>{{ message }}</strong>
						</p>
					</div>
			{% endfor %}
		{% endif %}


    <div class="row" style="width: 100vw;">
				<!-- {% if user.is_authenticated %}
					<p class="logged-in-p">
						Olá {{ user.username }} seja bem vindo, o que deseja fazer hoje? 
						<span class="sair"><a href="{% url 'account:logout' %}">Sair</a></span>
					</p>
				{% endif %} -->
		
		<div class="container mb-3" style="padding-bottom: 50px;">
        	{% block content %}
			{% endblock %}
			
		</div>
	</div>
    <div class="container" style="border-radius: 10px; background-color: #eee; box-shadow: 10px; box-shadow: 0px 0px 7px rgba(0, 0, 0, 0.842); max-width: 500px;">
        <div class="row">
            <div class="col-md-10 m-auto" style>
                {% block formulario %} {% endblock %}
            </div>
        </div>
    </div>

	<div class="footer">
		<footer >Prática de Lembrar &copy; 2020</footer>
	</div>

	<!-- JS com Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	
	<!-- Limpar sessionStorage para não causar erro na conta dos tempos -->
	<!-- sessionStorage só limpa quando a aba é fechada ou com a função clear -->
    <script type="text/javascript">
        sessionStorage.clear()
    </script>
	
</body>
</html>

templates/base_arvore.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8" />
	
	<link href="{% static 'css/style.css' %}" rel="stylesheet">

	<link rel="icon" href="{% static 'media/pratica_de_lembrar_icone.png' %}" />
	<link
		rel="stylesheet"
		href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
	/>
	<link
		rel="stylesheet"
		href="https://fonts.googleapis.com/icon?family=Material+Icons"
	/>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<meta
		name="viewport"
		content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"
	/>

	<title>Prática de Lembrar</title>
</head>

<body class='PaginaInicial' >

    <div class="container mt-5" style="max-width: 500px;">
        <div class="row">
            <div class="col-md-10 m-auto" style>
                {% block formulario %} {% endblock %}
            </div>
        </div>
    </div>


	<!-- JS com Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	
</body>
</html>

templates/navbar.html
{% load static %}

<!-- <header>
  <div class="cont grid-nav"; style="vertical-align: auto;">
    <ul>
      <a href="/" class="logo">
        <img src= "{% static 'media/pratica_de_lembrar.png' %}" width="81" height="50" alt="Prática de Lembrar">
      </a>
      <a style="text-decoration: none;" href="{% url 'blog:about' %}"><li> Quem Somos</li></a>
      {% if user.is_authenticated %}

      {% endif %}
  </ul>
    <ul>
      {% if not user.is_authenticated %}
        <a href="{% url 'account:register' %}"><li>Registrar</li></a>
        <a href="{% url 'account:login' %}"><li class="login">Entrar</li></a>
      {% else %}
          <a href="{% url 'account:perfilVisualizar' %}"><li>Perfil de {{user.username}}</li></a>
          <a href="{% url 'account:logout' %}"><li>Sair</li></a>
      {% endif %}
    </ul>
    <p class="hamburguer">&#9776;</p>
  </div>
</header> -->



<div style="background-color: #343a40;">
<div style="max-width: 1200px;margin:auto; background-color: #343a40;">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
    <a class="navbar-brand" href="/" >
        <img src= "{% static 'media/pratica_de_lembrar_mod.png' %}" width="81" height="50" alt="Prática de Lembrar">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'blog:home' %}">Página Inicial</a>
            <a class="nav-item nav-link" href="{% url 'blog:about' %}">Quem somos</a>
            {% if user.is_authenticated and not user.is_superuser%}
              <a class="nav-item nav-link" href="{% url 'blog:iniciar'%}">Questionário</a>
             
            {% endif %}

        </div>
        <div class="navbar-nav">
          {% if user.is_authenticated and not user.is_superuser%}
            <a class="nav-item nav-link" href="{% url 'account:perfilVisualizar' %}">Perfil de {{user.username}}</a>
          {% endif %}
          {% if user.is_superuser %}
            <a class="nav-item nav-link" href="{% url 'blog:testar' %}">Testar Questionários</a>
          {% endif %}
          {% if not user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'account:register' %}">Registrar</a>
            <a class="nav-item nav-link" href="{% url 'account:login' %}">Entrar</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'account:logout' %}">Sair</a>
          {% endif %}
        </div>
      
    </div> 

  </nav>
</div>
</div>